openapi: 3.0.3
info:
  title: Query broker API
  version: 1.0.0
  description: API that throws query to SQLite3 DSBM
paths:
  /api/{req}:
    get:
      operationId: api_retrieve
      parameters:
      - in: path
        name: req
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
